### ISSUE TITLE
MLR estimator not producing any results different from the ML estimator

### ISSUE THREAD

**Issue by WillemSleegers** [melissagwolf/dynamic#10]
Hi,

I was happy to see that the `cfaHb()` function now has support for various estimators, so I tried it out. Specifically, I tried out the following code:

```
library(dynamic)

dat <- lavaan::HolzingerSwineford1939
lavmod <- "F1 =~ x1 + x2 + x3
           F2 =~ x4 + x5 + x6
           F3 =~ x7 + x8 + x9"
fit <- lavaan::cfa(lavmod, dat)
cfaHB(fit, reps = 1)
lavaan::fitmeasures(fit, c("chisq", "df", "pvalue", "srmr", "rmsea", "cfi"))

fit_r <- lavaan::cfa(lavmod, dat, estimator = "MLR")
cfaHB(fit_r, reps = 1, estimator = "MLR")
lavaan::fitmeasures(
  fit_r,
  c(
    "chisq.scaled", "df.scaled", "pvalue.scaled", "srmr", "rmsea.robust",
    "cfi.robust"
  )
)
```

I expected the results of the two `cfaHB()` calls to differ, but they seem to be identical. In fact, the `cfaHB()` call with `estimator = "MLR"` is returning the exact same fit measure values as the default one, even though it should be returning the scaled/robust versions of the fit measures (if I understand correctly). 

Am I missing something or is there a bug here?

**Comment by melissagwolf** [comment]
The GitHub version is currently in beta and we're testing some things out. `nnorHB` is the correct function to use.

**Comment by WillemSleegers** [comment]
Thanks for that. I think as a user I find that quite confusing (also see this [tweet](https://twitter.com/dmcneish18/status/1650792437030469632?s=20), which added to my confusion).

**Comment by dmcneish18** [comment]
Conceptually, MLR = c*ML where c is correction factor for non-normality. cfaOne and cfaHB generate from normal distributions, in which case c=1 because there is no non-normality. So MLR = ML in these functions. The functions *are* using MLR as indicated by that tweet, there is just no difference between MLR and ML with the type of data being generated by these functions. 

If it makes it less confusing, I added a warning about MLR with functions that simulate from a normal distribution to inform users that MLR = ML with these functions and that the nnor group of functions may be more useful if the goal is to derive cutoffs that are sensitive to non-normality.

**Comment by WillemSleegers** [comment]
Thanks; I think a warning is useful.

**Comment by melissagwolf** [comment]
Thanks for the helpful feedback as always @WillemSleegers! We've added a few clarifying messages for other estimators as well. Please continue to let us know if you run into bugs or something is unclear - we really appreciate it.
