### ISSUE TITLE
Can likertHB be used in a bifactor model?

### ISSUE THREAD

**Issue by ddddddys** [melissagwolf/dynamic#19]
I was trying to use this dynamic cutoff in my data, which is a 7-point Likert scale.

I entered the code as follows:
cfadata <- read_sav("xxx.sav")
lavmod <- " g = H1 + H5 + H6 + H7 + S1 + S8 + S2 + S3 + S4 + S6 + S7 + H2 + C1 + C2 + C3 + C4 + C5 + C6
            f1 =~ H1 + H5 + H6 + H7 + S1 + S8
            f2 =~ S2 + S3 + S4 + S6 + S7 + H2
            f3 =~ C1 + C2 + C3 + C4 + C5 + C6
           "
fit <- lavaan::cfa(lavmod,cfadata)
summary(fit, fit.measures = TRUE, standardized = TRUE)
dynamic::likertHB(fit, data=cfadata,plot=T, estimator="ML")

But I got this error. Can anyone suggest how to solve it?
Error in `purrr::map()`:
ℹ In index: 1.
Caused by error:
! lavaan->ldw_parse_step2():  
   formula without valid operator at line 8, pos 1
NA
^
Run `rlang::last_trace()` to see where the error occurred.
Warning message:
lavaan->lav_model_vcov():  
   Could not compute standard errors! The information matrix could not be inverted. This may be a 
   symptom that the model is not identified. 
> rlang::last_trace()
<error/purrr_error_indexed>
Error in `purrr::map()`:
ℹ In index: 1.
Caused by error:
! lavaan->ldw_parse_step2():  
   formula without valid operator at line 8, pos 1
NA
^
---
Backtrace:
     ▆
  1. └─dynamic::likertHB(fit, data = dat, plot = T, estimator = "ML")
  2.   └─dynamic:::multi_df_likert(model9, data, n, estimator, reps)
  3.     └─dynamic:::multi_fit_likert(model, data, n, estimator, reps)
  4.       └─purrr::map(...)
  5.         └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
  6.           ├─purrr:::with_indexed_errors(...)
  7.           │ └─base::withCallingHandlers(...)
  8.           ├─purrr:::call_with_cleanup(...)
  9.           └─dynamic (local) .f(.x[[i]], ...)
 10.             └─simstandard::sim_standardized(...)
 11.               └─simstandard::sim_standardized_matrices(m, ...)
 12.                 └─lavaan::lavParTable(m, fixed.x = F)
 13.                   └─lavaan::lavParseModelString(model.syntax = model, debug = FALSE)
 14.                     └─lavaan:::ldw_parse_model_string(...)
 15.                       └─lavaan:::ldw_parse_step2(modellist, modelsrc, types)
 16.                         └─lavaan:::lav_msg_stop(...)
 17.                           └─base::stop(msg, call. = FALSE, domain = NA)

Thanks in advance!

**Comment by dmcneish18** [comment]
Any of the functions ending in "HB" (including `likertHB`) are not designed for bifactor models. These functions simulate hypothetical misspecification using specific omitted paths. For bifactor models, the specific paths that would presumably be of interest require different restrictions than for a typical CFA model. The function will sometimes work when applied to a bifactor model if the correct paths happen to be selected by chance, but other times it will breakdown. 

The direct discrepancy DFI method is better equipped for bifactor models because it is unaffected by nuances of specific omitted paths in a bifactor model. Unfortunately, the direct discrepancy method does not work well with the intermediate matrix method needed to simulate correlation matrices of ordinal data treated as continuous, so the the direct discrepancy DFI method would either need to be treat the data as categorical or non-normal continuous (which is less problematic when simulating correlation matrices for ordinal data treated as  continuous, but can still sometimes run into problem in some models).
